# Generated by Django 2.2.1 on 2019-06-04 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.User')),
            ],
        ),
    ]
